version: '3.8'
services:
  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    ports:
      - "5000:5000"
    networks:
      - ml_network
    environment:
      BACKEND_STORE_URI: sqlite:///mlflow.db
      ARTIFACT_ROOT: /mlflow/artifacts
    volumes:
      - ./mlruns:/mlflow
    command: mlflow server --host 0.0.0.0 --port 5000

  train:
    build:
      context: .
      dockerfile: docker_training/Dockerfile
    depends_on:
      - mlflow
    networks:
      - ml_network
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
      - PYTHONPATH=/app
    command: ["python", "/app/src/model/train_mlflow.py"]

  serving:
    build:
      context: .
      dockerfile: docker_serving/Dockerfile
    depends_on:
      - mlflow
    networks:
      - ml_network
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
      - PYTHONPATH=/app
    ports:
      - "8002:8002"

networks:
  ml_network:
    driver: bridge