apiVersion: v1
kind: Service
metadata:
  name: fever-serving-service
  labels:
    app: fever-serving
spec:
  selector:
    app: fever-serving
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8002
      nodePort: 30082 
    - name: prometheus
      protocol: TCP
      port: 9092
      targetPort: 9092
      nodePort: 30092
  type: NodePort
